name: edu_rev_app
description: A Flutter recreation of the EduRev UKG app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


